# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mixed' do
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'SystemServices'

  target 'MixedTests' do
    inherit! :search_paths
    pod 'Firebase'
  end

end
